# Sets up Home Assistant.
#
# Basically, everything that doesn't have to be in the
# main configuration.yaml.
#
homeassistant:
  # Lets me customize individual entities
  customize: !include_dir_merge_named ../customizations/entities