id: kodi_movie_stopped_at_night
alias: Kodi Movie Stopped At Night
description: ''
trigger:
- platform: state
  entity_id: media_player.kodi
  from: playing
  to: idle
condition:
  condition: or
  conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
action:
- service: scene.turn_on
  data:
    entity_id: scene.movie_paused
    transition: 3
mode: single
