alias: 'Guests phone off'
condition:
  condition: state
  entity_id: input_boolean.house_guests
  state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.guest_phone_connected
    to: 'off'
action:
   service: input_boolean.turn_off
   data:
     entity_id: input_boolean.house_guests