id: 'no_guests_sensor_open'
alias: No Guests Sensor Open notify
description: ''
trigger:
- platform: state
  entity_id: 
    - binary_sensor.wyzesense_basement_w_window
    - binary_sensor.wyzesense_basement_e_window
    - binary_sensor.wyzesense_bathroom_window
    - binary_sensor.wyzesense_front_door
    - binary_sensor.wyzesense_garage_door
    - binary_sensor.wyzesense_kitchen_window
    - binary_sensor.wyzesense_lr_nw_window
    - binary_sensor.wyzesense_lr_sw_window
    - binary_sensor.wyzesense_sliding_door
  from: 'off'
  to: 'on'
condition: 
- condition: state
  entity_id: sensor.someone_home
  state: 'false'
action:
- data_template:
    message: "{{ trigger.from_state.attributes.friendly_name }} was opened while no one was at home"
    title: Security
    data:
      ttl: 0
      priority: high
      channel: Security
  service_template: notify.all_phones