id: clear_deebot_error_while_vacuuming
alias: Deebot Automatic Error Clear
trigger:
  - platform: state
    entity_id: vacuum.deebot
    attribute: status
    from: auto
    to: stop
mode: single
action:
  - delay: 00:00:01
  - choose:
      # If switch on and battery greater than 30
      - conditions: >
          {{ is_state('input_boolean.vacuum_upstairs', 'on') and 
            state_attr('vacuum.deebot','battery_level') > 30 and
            state_attr('vacuum.deebot','status') != "returning" }}
        sequence:
        - service: vacuum.turn_on
          data: {}
          entity_id: vacuum.deebot
        - delay:
            seconds: 1
        - service: vacuum.set_fan_speed
          data: {
              fan_speed: 'high'
          }
          entity_id: vacuum.deebot
      # If switch is on and battery less than 30
      - conditions: >
          {{ state_attr('vacuum.deebot','status') == "returning" or
            (is_state('input_boolean.vacuum_upstairs', 'on') and 
            state_attr('vacuum.deebot','battery_level') < 30) }}
        sequence:
        - service: vacuum.turn_off
          data: {}
          entity_id: vacuum.deebot
        - service: input_boolean.turn_off
          data: {}
          entity_id: input_boolean.vacuum_upstairs
        - service: vacuum.return_to_base
          data: {}
          entity_id: vacuum.deebot