alias: Set Kitchen Ready to Vacuum
trigger:
  platform: event
  event_type: tag_scanned
  event_data:
    tag_id: kitchen_tag
action:
  service: input_boolean.turn_on
  data:
    entity_id: input_boolean.kitchen_ready_to_vacuum