id: '1572198883759'
alias: TV Light Off
description: ''
trigger:
- entity_id: media_player.shield_tv
  platform: state
  to: 'off'
- entity_id: media_player.shield_tv
  platform: state
  to: 'idle'
condition: []
action:
- data:
    entity_id: light.tv_white
    transition: 3
  service: light.turn_off
- data:
    entity_id: light.tv_color
    transition: 3
  service: light.turn_off