id: 'doorbell_displays'
alias: Doorbell Displays
description: 'Casts doorbell video stream to kitchen display'
trigger: []
action:
- data:
    media_player: media_player.kitchen_display
  entity_id: camera.door_bell
  service: camera.play_stream
- delay:
    seconds: 15
- data: {}
  entity_id: media_player.kitchen_display
  service: media_player.turn_off
- data: {}
  entity_id: media_player.kitchen_display
  service: media_player.turn_off