id: 'doorbell_phones'
alias: Doorbell Phones
description: ''
trigger: []
action:
- data_template:
    data:
      image: >-
        {{ states.input_text.base_url.state }}/local/snapshots/front_door_bell.jpg?{{ states.automation.doorbell_ring.last_triggered }}
      priority: high
      ttl: 0
    message: Someone rang your doorbell
    title: Doorbell
  service: notify.all_phones