id: 'door_bell_speakers'
alias: Doorbell Speakers
description: ''
trigger: []
condition:
- after: 08:00:00
  before: '20:30:00'
  condition: time
action:
  - data:
      command: Knock Knock
    service: rest_command.assistant_broadcast
# action:
# - service: media_player.volume_set
#   entity_id: group.house_speakers_group
#   data:
#     volume_level: 0.0
# - service: media_player.turn_on
#   entity_id: group.house_speakers_group
# - service: media_player.play_media
#   entity_id: group.house_speakers_group
#   data_template:
#     media_content_id: >-
#       {{ states.input_text.local_base_url.state }}/local/Doorbell.mp3
#     media_content_type: music
# - delay:
#       seconds: 12
# - service: media_player.volume_set
#   entity_id: group.house_speakers_group
#   data:
#     volume_level: 0.4
# - data:
#     volume_level: 0.7
#   entity_id: media_player.living_room_speaker
#   service: media_player.volume_set
# - service: media_player.turn_off
#   entity_id: group.house_speakers_group