id: 'door_bell_speakers'
alias: Doorbell Speakers
description: ''
trigger: []
condition:
- after: 08:00:00
  before: '20:30:00'
  condition: time
action:
  - service: script.turn_on
    entity_id: script.google_announce
    data:
      variables:
        entity: group.house_speakers_group
        message: "Knock knock"
        volume: 0.5

  # - data:
  #     command: Knock Knock
  #   service: rest_command.assistant_broadcast