id: '1584983631507'
alias: Test Notification
description: ''
trigger:
- platform: webhook
  webhook_id: test_notification
condition: []
action:
- service: media_player.volume_set
  entity_id: media_player.office_speaker
  data:
    volume_level: 0.0
- service: media_player.turn_on
  entity_id: media_player.office_speaker
- service: media_player.play_media
  entity_id: media_player.office_speaker
  data:
    media_content_id: https://assistant.borup.duckdns.org/local/Doorbell.mp3
    media_content_type: music
- service: media_player.turn_off
  entity_id: media_player.office_speaker