id: '1584983631507'
alias: Test Notification
description: ''
trigger:
- platform: webhook
  webhook_id: test_notification
condition: []
action:
# - data:
#     filename: /home/homeassistant/.homeassistant/www/snapshots/front_door_bell.jpg
#   entity_id: camera.door_bell
#   service: camera.snapshot
# - data:
#     data:
#       image: https://assistant.borup.duckdns.org/local/snapshots/front_door_bell.jpg?{{
#         states.automation.test_notification.last_triggered }}
#       priority: high
#       ttl: 0
#     message: Someone rang your doorbell
#     title: Doorbell
#   service: notify.mobile_app_nate_phone
- service: media_player.volume_set
  entity_id: media_player.office_speaker
  data:
    volume_level: 0.0
- service: media_player.turn_on
  entity_id: media_player.office_speaker
- service: media_player.play_media
  entity_id: media_player.office_speaker
  data:
    media_content_id: https://assistant.borup.duckdns.org/local/Doorbell.mp3
    media_content_type: music
- service: media_player.turn_off
  entity_id: media_player.office_speaker
# - delay:
#     milliseconds: 2000
# - service: media_player.volume_set
#   entity_id: media_player.office_speaker
#   data_template:
#     volume_level: >-
#       {% if now().hour < 20 and now().hour > 8 %}
#       0.4
#       {% else %}
#       0.4
#       {% endif %}
# # - data:
#     entity_id: media_player.office_speaker
#     message: this is a test
#   service: tts.google_translate_say