id: 'doorbell_tvs'
alias: Doorbell TVs
description: ''
trigger: []
action:
- data_template:
    data:
      file:
        url: >-
          {{ states.input_text.base_url.state }}/local/snapshots/front_door_bell.jpg?{{ states.automation.doorbell_ring.last_triggered }}
    message: Someone rang your doorbell
    title: Doorbell
  service: notify.shield_notification