id: 'doorbell_watcher_volume_set'
alias: Doorbell Watcher Volume Set
description: 'Watches to see if the doorbell group starts playing the mp3 to adjust volume'
trigger:
  - entity_id: sensor.doorbell_last_triggered
    platform: state
# - entity_id: binary_sensor.doorbell_playing
#   from: 'off'
#   platform: state
#   to: 'on'
condition: []
action:
- delay:
    milliseconds: 2000
- service: media_player.volume_set
  entity_id: media_player.doorbell_group
  data_template:
    volume_level: >-
      {% if now().hour < 20 and now().hour > 8 %}
      0.6
      {% else %}
      0.4
      {% endif %}