id: 'kids_stay_in_bed'
alias: Kids Stay In Bed
description: ''
trigger: []
condition: []
action:
- data:
    brightness: 10
    rgb_color:
      - 255
      - 0
      - 0
    entity_id: light.kids_light
  service: light.turn_on