id: 'kids_light_turn_off'
alias: Kids Light Turn Off
description: ''
trigger: 
    platform: time
    at: "09:00:00"
condition: []
action:
- data:
    entity_id: light.kids_light
  service: light.turn_off