id: 'git_status_hook'
alias: Git Status Hook
description: 'Updates the git status'
trigger:
- platform: webhook
  webhook_id: git_status
action:
   - service: mqtt.publish
     data_template:
       topic: homeassistant/git_status_added
       payload: '{{ trigger.json.add_count }}'
       retain: true
   - service: mqtt.publish
     data_template:
       topic: homeassistant/git_status_added/attributes
       payload_template: '{{ trigger.json.add | tojson }}'
       retain: true
   - service: mqtt.publish
     data_template:
       topic: homeassistant/git_status_modified
       payload: '{{ trigger.json.modify_count }}'
       retain: true
   - service: mqtt.publish
     data_template:
       topic: homeassistant/git_status_modified/attributes
       payload_template: '{{ trigger.json.modify | tojson }}'
       retain: true
   - service: mqtt.publish
     data_template:
       topic: homeassistant/git_status_deleted
       payload: '{{ trigger.json.delete_count }}'
       retain: true
   - service: mqtt.publish
     data_template:
       topic: homeassistant/git_status_deleted/attributes
       payload_template: '{{ trigger.json.delete | tojson }}'
       retain: true