id: 'git_commit'
alias: Git Commit
description: ''
trigger: []
action:
- service: shell_command.git_commit
- service: input_text.set_value
  data:
    entity_id: input_text.commit_message
    value: ""
- service: shell_command.git_update